return {
  time = require ('widget.time'),
  btn = {
    firefox = require ('widget.button.firefox'),
    discord = require ('widget.button.discord'),
    terminal = require ('widget.button.terminal'),
    rofi = require ('widget.button.rofi_launcher'),
    notif = require ('widget.button.notif'),
    tag_switch = require ('widget.button.tag_switch'),
    wall = require ('widget.button.wall'),
    power = require ('widget.button.power'),
    settings = require ('widget.button.settings'),
    files = require ('widget.button.files'),
  },
  launchers = require ('widget.launchers'),
  profile = require ('widget.profile'),
  tasklist = require ('widget.tasklist'),
  motd = require ('widget.motd'),
  music = require ('widget.music'),
  bars = require ('widget.bars'),
  charts = require ('widget.charts'),
  actions = require ('widget.actions'),
  weather = require ('widget.weather'),
  power = require ('widget.power'),
  updates = require ('widget.updates'),
}
